version: '2'

services:
  web:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=mariadb:3306
      - DB_NAME=curldump
      - DB_USER=curldump
      - DB_PASSWD=xebF7994i4hu
    restart: always
    volumes: 
      - ./script/:/var/www/html
    ports:
      - "3000:80"
      - "2222:22"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Nw9frt3w43XJ
      - MYSQL_DATABASE=curldump
      - MYSQL_USER=curldump
      - MYSQL_PASSWORD=xebF7994i4hu
    volumes:
      - ./mariadb/:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
      - "3001:80"
    volumes:
     - /sessions